# Generated by Django 3.0.5 on 2021-09-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='workerStatus',
            new_name='isAccepted',
        ),
    ]
