# Generated by Django 3.0.5 on 2021-09-11 12:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20210911_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='work_request', to='work.Request'),
            preserve_default=False,
        ),
    ]
