# Generated by Django 3.0.5 on 2021-09-11 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20210911_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_request', to='work.Request'),
        ),
    ]
