# Generated by Django 3.0.5 on 2021-09-11 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0007_auto_20210911_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='seeker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='req_seeker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='req_worker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work',
            name='request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='work_request', to='work.Request'),
            preserve_default=False,
        ),
    ]
