# Generated by Django 3.0.5 on 2021-09-12 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210911_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_coordinates', to='user.Coordinates'),
        ),
    ]
